### ISSUE TITLE
New to GitHub, need help :)

### ISSUE THREAD

**Issue by NotChztn** [Holfz/ApexRPC#15]
Hello! I'm kinda new to GitHub and don't have much experience with anything here.

From what I understand, I can fork this project to basically clone it, right?

I edited the Translation.js to change "Chilling in lobby..." to just say "In lobby" and saved it. But how do I like, build this into an .exe then? (All I literally figured out by myself is to edit that thing through notepad)

**Comment by Holfz** [comment]
Welcome to GitHub!

Firstly, You can fork this project to edit on your own.

For running or compiling the project, You need to have [https://nodejs.org/en](Node.js) and install dependencies by running `npm i` on the project directory.

Then if you want to compile the project, You would run `npm run build` and the compiled exe will located in the project directory

**Comment by NotChztn** [comment]
I've already had NodeJS installed. But where can I input the `npm i`? As well as `npm run build`?

**Comment by Holfz** [comment]
Hello, You can run it in the project directory using `cmd`, `PowerShell` (Shift + Right Click inside the folder that the project contained)

**Comment by NotChztn** [comment]
I'm getting a "'nexe' is not recognized as an internal or external command,operable program or batch file." error after running a `npm run build` :(

**Comment by Holfz** [comment]
Sorry for missing that, You would need to run `npm i` (If you haven't done that yet) and also **`npm i nexe -g`** to install dependencies and nexe

**Comment by NotChztn** [comment]
That worked! It was a success! Thank you so much!!

**Comment by NotChztn** [comment]
Just wanted to ask, where can I change the "In the party alone" texts and stuff? Cause I can only find the Line 1 of the RPC from Translation.js hehe

**Comment by NotChztn** [comment]
> Just wanted to ask, where can I change the "In the party alone" texts and stuff? Cause I can only find the Line 1 of the RPC from Translation.js hehe

Main.js, my god, I just had to look for it.

**Comment by Holfz** [comment]
My bad I've hardcoded that in XD

**Comment by NotChztn** [comment]
![image](https://github.com/Holfz/ApexRPC/assets/87931918/79490564-43ff-45a0-84ff-d7fd3efb379f)
I mean, this is all that I can do, when I viewed the .js files. HAHAHAHA. Great work man!
