### ISSUE TITLE
Adding Ranked, Arena, Ranked Arena Support

### ISSUE THREAD

**Issue by tzunni** [Holfz/ApexRPC#2]
I'm trying to see if I can implement support for these game modes. I was wondering how you found the tags for Trio and Duo?

**Comment by Holfz** [comment]
Hi, I found by inspect the rich presence data from steam, You can try logging `user.rich_presence` in on the `main.js` line 72

You can try to implement the support and create the PR, I can help you look at that as well!

**Comment by Holfz** [comment]
Also the SteamDB provide you some on the [localization page](https://steamdb.info/app/1172470/localization/) too
