### ISSUE TITLE
Doesn't work on desertlands 

### ISSUE THREAD

**Issue by VNRARA** [Holfz/ApexRPC#7]
Doesn't update my status at all. 

![image](https://user-images.githubusercontent.com/3942672/174498137-8599ccd8-c937-48ea-be70-0aac34a4df4a.png)

**Comment by Holfz** [comment]
Hello, Thanks for your interest in this project.

Can you let me know which mode/map do you have played that not working ?

**Comment by LTTS1991** [comment]
Trios on any map.

**Comment by VNRARA** [comment]
Trios on any map. It doesn't even show when in the lobby.

**Comment by Holfz** [comment]
`mp_rr_desertlands_mu3` is "World's Edge" and should be parse as `mp_rr_desertlands`

I can see typo on [Termination.js](https://github.com/Holfz/ApexRPC/blob/main/Constants/Termination.js#L2) `m3` should be `mu3`

Seems a-bit weird... This should only not working on "World's Edge". 

Could you please try on "Storm Point" ?

---
Works fine for me on The range and Lobby.

![image](https://user-images.githubusercontent.com/32639831/174498506-5cf89af9-676a-41b9-a026-3d740926e778.png)
![image](https://user-images.githubusercontent.com/32639831/174498512-9a487ee3-5d07-454a-9d14-c2903d0caf37.png)

also TRIOS: Storm Point

![image](https://user-images.githubusercontent.com/32639831/174498537-985cc163-6ac4-4b18-a909-efa15183fb3f.png)

**Comment by VNRARA** [comment]
Storm point seems to work. 

![image](https://user-images.githubusercontent.com/3942672/174500053-93690117-f3e0-4651-bdff-b6db717a0dfc.png)

**Comment by Holfz** [comment]
Can you please try [v1.0.3a](https://github.com/Holfz/ApexRPC/releases/tag/v1.0.3a) that was fixed the typo in the termination string.
